#!/usr/bin/lua
--[[

	Part of AREDN -- Used for creating Amateur Radio Emergency Data Networks
	Copyright (C) 2019 Darryl Quinn
	See Contributors file for additional contributors

	This program is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation version 3 of the License.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program.	If not, see <http://www.gnu.org/licenses/>.

	Additional Terms:

	Additional use restrictions exist on the AREDN(TM) trademark and logo.
		See AREDNLicense.txt for more info.

	Attributions to the AREDN Project must be retained in the source code.
	If importing this code into a new or existing project attribution
	to the AREDN project must be added to the source code.

	You must not misrepresent the origin of the material contained within.

	Modified versions must be modified to attribute to the original source
	and be marked in reasonable ways as differentiate it from the original
	version

--]]

require("uci")
require("aredn.uci")
require("aredn.utils")
require("nixio")
require("iwinfo")
local http = require("aredn.http")
local aredn_olsr = require("aredn.olsr")
local aredn_info = require("aredn.info")
local json = require("luci.jsonc")

-- Function extensions
os.capture = capture

-------------------------------------
-- GET querystring/cmdline handler
-------------------------------------
function process_get_request(topiccomps)
	info['topics']={}

	for topic, comps in pairs(topiccomps) do
		if not setContains(info['topics'],topic) then
			info['topics'][topic]={}
		end

		if topic=="apiprotected" then
			info['topics'][topic]=nil
			info['api_help']="AREDN Protected API. This API's primary function is to be used by the Web UI and calls are protected via uhttpd"
		elseif topic=="dhcp" then
			for i,comp in pairs(comps:split(',')) do
				if comp=="currentleases" then
					info['topics'][topic][comp]=aredn_info.getCurrentDHCPLeases()
				end
			end
		end
	end
end

-------------------------------------
-- POST json handler
-------------------------------------
local function process_post_request(jsondata)
	if setContains(jsondata, "page") and setContains(jsondata, "data") then
		if jsondata['page']=="basic_setup" then
			local ph = require("aredn.page.handler.basic_setup")
			info['result'] = ph.page_handler(jsondata['data'])
		elseif jsondata['page']=="port_forwarding" then
			local ph = require("aredn.page.handler.port_forwarding")
			info['result'] = ph.page_handler(jsondata['data'])
		end
	else
		info['error']="request must contains valid 'page' and 'data' elements"
	end
end

-- ==== MAIN =====
ctx = uci.cursor()
if not ctx then
	error("Failed to get uci cursor")
end

info={}

-- get headers
local headers = http.get_headers()
local qsset = {}

if (arg[1]~=nil and arg[2]~=nil) then			-- commandline call support
	qsset[arg[1]]=arg[2]
	process_get_request(qsset)
elseif headers.REQUEST_METHOD == "GET" then		-- GET method
	qs=headers.QUERY_STRING
	if qs~="" then
		qsset=parseQueryString(qs)
	else
		qsset["apiprotected"]="help"
	end
	process_get_request(qsset, info)
elseif headers.REQUEST_METHOD == "POST" then	-- POST method
	if headers.CONTENT_TYPE == "application/json" then
		local body = http.get_post_body()
		local body_json = json.parse(body)
		process_post_request(body_json)
	else
		print("Content_Type MUST be application/json")
	end
else
	print("ERROR: request method can be either POST or GET or from commandline as: /apiprotected topic component")
	os.exit()
end

-- Output the HTTP header for JSON
-- json_header()
http.json_header()

-- Output the info table as json
print(json.stringify(info,true))